### ISSUE TITLE
Payment Failed! System error 

### ISSUE THREAD

**Issue by dummyltpl** [slykar/phonegap-paypal#1]
![screenshot_2014-10-18-16-00-29](https://cloud.githubusercontent.com/assets/9046174/4689614/65d36076-56c2-11e4-9f2a-ea083387d92f.png)

I am using spinin/phonegap-paypal plugin for my phonegap android app. I downloaded the plugin, integrated with the mobile app, then tried using the payment on sandbox mode. I was able to do the payment till yesterday. But suddenly it has stopped working. From my app I am able to login to the Paypal account and go to the dashboard, but when I click on 'Send Payment' , I get an error- 'Payment Failed: System Error, Please try again later '. Can anyone please tell me what must be going wrong? Alteast can any one let me know what are the possible reasons for this to happen, so that I can check each of the points on code level.

Thanks in advance.

**Comment by slykar** [comment]
Hi fellow,

I've found a related issue here: https://github.com/paypal/PayPal-Android-SDK/issues/49

You can try updating the PayPal SDK, but it might be problem with their sandbox.

**Comment by dummyltpl** [comment]
Hi fellow,

Could you please mention the steps for updating the PayPal SDK.

**Comment by slykar** [comment]
You can find PayPa Android SDK JAR here: https://github.com/paypal/PayPal-Android-SDK/tree/master/libs
Just replace the file in `libs/android`

I'm just afraid the problem is on the PayPal's side, so it might not really help you.
It's been some time since last time I had to use PayPal integration in PhoneGap, so I'm not able to play with it.

Good luck.
